# Generated by Django 5.1.2 on 2024-10-24 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_remove_employee_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarrangement',
            name='team',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='work_arrangements', to='employee_app.team'),
        ),
    ]
