name: Django CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Admin@123
          POSTGRES_DB: employee_app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django_user -d django_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Current Directory
      run: |
          echo "Current Directory:"
          pwd
          echo "Contents:"
          ls -la

    - name: Check Directory Before CD
      run: |
          echo "Checking if employee_management_project exists..."
          if [ -d "employee_management_project" ]; then
            echo "Directory exists."
          else
            echo "Directory does not exist."
          fi

    - name: Wait for Postgres to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until pg_isready -h localhost -U django_user -d django_db; do
          echo "Postgres is unavailable - sleeping"
          sleep 1
        done
        echo "Postgres is up - continuing"
        
    - name: Run Migrations
      run: python employee_management_project/manage.py migrate
      
    - name: Running Test Cases 
      run: |
        python employee_management_project/manage.py test



